// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjXfb0GvrjvPup7DI2siRsveAWzDnIas',
    appId: '1:441311299144:web:137a1fcc6ab706f918fa7d',
    messagingSenderId: '441311299144',
    projectId: 'linkedin-clone-4e22b',
    authDomain: 'linkedin-clone-4e22b.firebaseapp.com',
    storageBucket: 'linkedin-clone-4e22b.appspot.com',
    measurementId: 'G-449YYYF873',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBC0fH6nanMwLeDK32V75h2PIcfeeYqbQ',
    appId: '1:441311299144:android:f7a4122a9905312818fa7d',
    messagingSenderId: '441311299144',
    projectId: 'linkedin-clone-4e22b',
    storageBucket: 'linkedin-clone-4e22b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6YrmqQkyrlbuEgGAR1rtEwzTLa7qnGU',
    appId: '1:441311299144:ios:e257ad55dfcafbec18fa7d',
    messagingSenderId: '441311299144',
    projectId: 'linkedin-clone-4e22b',
    storageBucket: 'linkedin-clone-4e22b.appspot.com',
    iosBundleId: 'com.example.linkedinCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6YrmqQkyrlbuEgGAR1rtEwzTLa7qnGU',
    appId: '1:441311299144:ios:38fc1e181ff7817918fa7d',
    messagingSenderId: '441311299144',
    projectId: 'linkedin-clone-4e22b',
    storageBucket: 'linkedin-clone-4e22b.appspot.com',
    iosBundleId: 'com.example.linkedinCloneApp.RunnerTests',
  );
}
